service: AloPoliciaBackend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - dynamodb:*
        
      Resource: "*"

functions:
  backend:
    handler: src.lambda_function.lambda_handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements
  - serverless-dotenv
custom:
  pythonRequirements:
     dockerizePip: true

package:
  exclude:
    - ./**
  include:
    - src/**